export const DATA_MODEL_ENTITY_CREATED_EVENT_LOGGER_PREFIX =
  'DATA_MODEL_ENTITY_CREATED_EVENT';
export const DATA_MODEL_ENTITY_DELETED_EVENT_LOGGER_PREFIX =
  'DATA_MODEL_ENTITY_DELETED_EVENT';
export const DATA_MODEL_ENTITY_UPDATED_EVENT_LOGGER_PREFIX =
  'DATA_MODEL_ENTITY_UPDATED_EVENT';
export const CONNECT_TO_CWIRE_LOGGER_PREFIX = 'CONNECT_TO_CWIRE';
export const CONNECTION_ERROR_LOGGER_PREFIX = 'CONNECTION_ERROR';
export const DISCONNECT_TO_CWIRE_LOGGER_PREFIX = 'DISCONNECT_TO_CWIRE';
export const CONSTRUCT_REFERENCES_LOGGER_PREFIX = 'CONSTRUCT_REFERENCES';

export const FUNCTION_CALL_PERFORMANCE_LOGGER_PREFIX =
  'FUNCTION_CALL_PERFORMANCE';

export const API_LOGGER_PREFIX = 'API';

export const BULK_LOGGER_PREFIX = 'BULK_ACTION';
export const CREATE_ENTITY_LOGGER_PREFIX = 'CREATE_ENTITY_ACTION';
export const COUNT_ENTITY_LOGGER_PREFIX = 'COUNT_ENTITIES_ACTION';
export const UPDATE_ENTITIES_LOGGER_PREFIX = 'UPDATE_ENTITIES_ACTION';
export const REMOVE_ENTITIES_LOGGER_PREFIX = 'REMOVE_ENTITIES_ACTION';
export const FIND_ONE_ENTITY_LOGGER_PREFIX = 'FIND_ONE_ENTITY_ACTION';
export const FIND_ALL_ENTITY_LOGGER_PREFIX = 'FIND_ALL_ENTITIES_ACTION';
