"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataModelAction = exports.DataModelField = exports.DataModel = exports.CWire = void 0;
var CWire_1 = require("./CWire");
Object.defineProperty(exports, "CWire", { enumerable: true, get: function () { return CWire_1.CWire; } });
var DataModel_1 = require("./DataModel");
Object.defineProperty(exports, "DataModel", { enumerable: true, get: function () { return DataModel_1.DataModel; } });
var DataModelField_1 = require("./DataModelField");
Object.defineProperty(exports, "DataModelField", { enumerable: true, get: function () { return DataModelField_1.DataModelField; } });
var DataModelAction_1 = require("./DataModelAction");
Object.defineProperty(exports, "DataModelAction", { enumerable: true, get: function () { return DataModelAction_1.DataModelAction; } });
exports.default = CWire_1.CWire;
