export class WorkerNotFound extends Error {}
export class MissingRequiredPropertyError extends Error {}
export class WrongFieldTypeError extends Error {}
export class WrongActionTypeError extends Error {}
export class DataModelNotFoundError extends Error {}
export class DataModelFieldNotFoundError extends Error {}
export class DataModelActionNotFoundError extends Error {}
export class FeatureIsNotImplementedNow extends Error {}
export class WrongModelDetectedError extends Error {}
