export class WorkerNotFound extends Error {}
export class MissingRequiredPropertyError extends Error {}
export class WrongFieldTypeError extends Error {}
export class DuplicatedOptionsParsedError extends Error {}
export class WrongActionTypeError extends Error {}
export class DataModelNotFoundError extends Error {}
export class DataModelFieldNotFoundError extends Error {}
export class DataModelActionNotFoundError extends Error {}
export class CWireIsNotInitialised extends Error {}
export class FeatureIsNotImplementedNowError extends Error {}
export class WrongModelDetectedError extends Error {}
export class MultiplePrimaryFieldsAreNotAllowedError extends Error {}
export class MissingPrimaryFieldError extends Error {}
export class UnknownDataModelTypeError extends Error {}
export class WrongFieldReferenceError extends Error {}
